var compo = compo || {};
compo = {
		login_form : ()=>{
			return '<h2>로 그 인 폼</h2>'
			+' <form>'
			+'   <div class="imgcontainer">'
			+'     <img src="https://img1.daumcdn.net/thumb/R720x0.q80/?scode=mtistory&fname=http%3A%2F%2Fcfile27.uf.tistory.com%2Fimage%2F2466D94653EC5DBD29E64E" alt="Avatar" class="avatar">'
			+'   </div>' 
			+'   <div class="container">'
			+'     <label for="uname"><b>아이디</b></label>'
			+'     <input id="id" type="text" placeholder="Enter Username" name="uname" value="as" required>'
			+'     <label for="psw"><b>비밀번호</b></label>'
			+'     <input id="pw" type="password" placeholder="Enter Password" name="psw" value="1234" required>'
			+'     <button type="submit">로그인</button>'
			+'     <label>'
			+'       <input type="checkbox" checked="checked" name="remember"> 아이디 기억하기'
			+'     </label>'
			+'   </div>'
			+'   <div class="container" style="background-color:#f1f1f1">'
			+'     <button type="button" class="join_btn">회원가입하기</button>'
			+'     <span class="psw">Forgot <a href="#">password?</a></span>'
			+'   </div>'
			+' </form>'},
			
		cust_mypage : ()=>{
			return '<div class="w3-light-grey">'
            +	'<!-- Page Container -->'
            +'<div class="w3-content w3-margin-top" style="max-width:1400px;">'
            +'<!-- The Grid -->'
            +'<div class="w3-row-padding">'
            +'<!-- Left Column -->'
            +'<div class="w3-third">'
            +'<div class="w3-white w3-text-grey w3-card-4">'
            +'<div class="w3-display-container">'
            +'<img src="/w3images/avatar_hat.jpg" style="width:100%" alt="Avatar">'
            +'<div class="w3-display-bottomleft w3-container w3-text-black">'
            +'<h2>전서우</h2>'
            +'</div>'
            +'</div>'
            +'<div class="w3-container">'
            +'<p><i class="fa fa-briefcase fa-fw w3-margin-right w3-large w3-text-teal"></i>Designer</p>'
            +'<p><i class="fa fa-home fa-fw w3-margin-right w3-large w3-text-teal"></i>London, UK</p>'
            +'<p><i class="fa fa-envelope fa-fw w3-margin-right w3-large w3-text-teal"></i>ex@mail.com</p>'
            +'<p><i class="fa fa-phone fa-fw w3-margin-right w3-large w3-text-teal"></i>1224435534</p>'
          	+'<hr>'
          	+'<p class="w3-large"><b><i class="fa fa-asterisk fa-fw w3-margin-right w3-text-teal"></i>Skills</b></p>'
          	+'<p>Adobe Photoshop</p>'
          	+'<div class="w3-light-grey w3-round-xlarge w3-small">'
            +'<div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:90%">90%</div>'
            +'</div>'
            +'<p>Photography</p>'
            +'<div class="w3-light-grey w3-round-xlarge w3-small">'
            +'<div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:80%">'
            +'<div class="w3-center w3-text-white">80%</div>'
            +'</div>'
            +'</div>'
            +'<p>Illustrator</p>'
            +'<div class="w3-light-grey w3-round-xlarge w3-small">'
            +'<div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:75%">75%</div>'
            +'</div>'
            +'<p>Media</p>'
            +'<div class="w3-light-grey w3-round-xlarge w3-small">'
            +'<div class="w3-container w3-center w3-round-xlarge w3-teal" style="width:50%">50%</div>'
            +'</div>'
            +'<br>'
            +'<p class="w3-large w3-text-theme"><b><i class="fa fa-globe fa-fw w3-margin-right w3-text-teal"></i>"Languages"</b></p>'
            +'<p>English</p>'
            +'<div class="w3-light-grey w3-round-xlarge">'
            +'<div class="w3-round-xlarge w3-teal" style="height:24px;width:100%"></div>'
            +'</div>'
            +'<p>Spanish</p>'
            +'<div class="w3-light-grey w3-round-xlarge">'
            +'<div class="w3-round-xlarge w3-teal" style="height:24px;width:55%"></div>'
            +'</div>'
            +'<p>German</p>'
            +'<div class="w3-light-grey w3-round-xlarge">'
            +'<div class="w3-round-xlarge w3-teal" style="height:24px;width:25%"></div>'
            +'</div>'
            +'<br>'
            +'</div>'
            +'</div><br>'
            +'<!-- End Left Column -->'
            +'</div>'
            +'<!-- Right Column -->'
            +'<div class="w3-twothird">'
            +'<div class="w3-container w3-card w3-white w3-margin-bottom">'
			},
	cust_update : ()=>{
			return '<form style="border:1px solid #ccc">'
			+'  <div class="container">'
			+'    <h1>회원정보수정</h1>'
			+'    <p>Please fill in this form to leave an account.</p>'
			+'    <hr>'
			+'    <label><b>ID</b></label>'
			+'    <input type="text" placeholder="EnterID" name="id" value="as" "required"><br>'
			+'    <label><b>Password</b></label>'
			+'    <input type="text" placeholder="EnterPassword" name="password" value="1234" "required"><br>'
			+'    <label><b>phone</b></label>'
			+'    <input type="text" placeholder="EnterPhone" name="phone" "required"><br>'
			+'    <label><b>city</b></label>'
			+'    <input type="text" placeholder="EnterCity" name="city" "required"><br>'
			+'    <label><b>address</b></label>'
			+'    <input type="text" placeholder="EnterAddress" name="address" "required"><br>'
			+'    <label><b>postalcode</b></label>'
			+'    <input type="text" placeholder="EnterPostalcode" name="postalcode" "required"><br>'
			+'    <label>'
			+'      <input type="checkbox" checked="checked" name="remember" style="margin-bottom:15px">Remember me'
			+'    </label>'
			+'    <p>By creating an account you agree to our <a href="#" style="color:dodgerblue">Terms & Privacy</a>.</p>'
			+'    <div class="clearfix">'
			+'      <button type="button" class="cancelbtn">Cancel</button>'
			+'      <button id="update_btn" type="submit" class="updatebtn">Update</button>'
			+'    </div>'
			+'  </div>'
			+'</form>'},
	cust_leave : ()=>{
			return '<form style="border:1px solid #ccc">'
			+'  <div class="container">'
			+'    <h1>회원탈퇴</h1>'
			+'    <p>Please fill in this form to leave an account.</p>'
			+'    <hr>'
			+'    <label><b>ID</b></label>'
			+'    <input type="text" placeholder="EnterID" name="id" value="df" "required"><br>'
			+'	  <label><b>NAME</b></label>'
			+'    <input type="text" placeholder="EnterNAME" name="name" value="버나드박" "required"><br>'
			+'    <label><b>Password</b></label>'
			+'    <input type="text" placeholder="EnterPassword" name="password" value="1234" "required"><br>'
			+'    <label><b>ssn</b></label>'
			+'    <input type="text" placeholder="EnterSSN" name="ssn" value="940812-262513" "required"><br>'
			+'    <label>'
			+'      <input type="checkbox" checked="checked" name="remember" style="margin-bottom:15px">Remember me'
			+'    </label>'
			+'    <p>By leaving an account you agree to our <a href="#" style="color:dodgerblue">Terms & Privacy</a>.</p>'
			+'    <div class="clearfix">'
			+'      <button type="button" class="cancelbtn">Cancel</button>'
			+'      <button type="submit" id="leave_btn" class="signupbtn">Leave account </button>'
			+'    </div>'
			+'  </div>'
			+'</form>'},
	cust_join : ()=>{
		return '<form style="border:1px solid #ccc">'
			+'  <div class="container">'
			+'  <h1>회원가입</h1>'
			+'  <p>빠짐없이 작성해주세요</p>'
			+'  <hr>'
			+'  <label><b>ID</b></label>'
			+'  <input type="text" placeholder="EnterID" name="id" value="lee gang in" "required"><br>'
			+'	<label><b>NAME</b></label>'
			+'  <input type="text" placeholder="EnterNAME" name="name" value="lee gang in" "required"><br>'
			+'  <label><b>Password</b></label>'
			+'  <input type="text" placeholder="EnterPassword" name="password" value="1234" "required"><br>'
			+'  <label><b>ssn</b></label>'
			+'  <input type="text" placeholder="EnterSSN" name="ssn" value="960111-1" "required"><br>'
			+'  <label><b>phone</b></label>'
			+'  <input type="text" placeholder="EnterPhone" name="phone" value="01012341111" "required"><br>'
			+'  <label><b>city</b></label>'
			+'  <input type="text" placeholder="EnterCity" name="city" value="부산" "required"><br>'
			+'  <label><b>address</b></label>'
			+'  <input type="text" placeholder="EnterAddress" name="address" value="학익동" "required"><br>'
			+'  <label><b>postalcode</b></label>'
			+'  <input type="text" placeholder="EnterPostalcode" name="postalcode" value="234" "required"><br>'
			+'  <label><b>photo</b></label>'
			+'  <input type="text" placeholder="EnterPhoto" name="photo" value="default" "required"><br>'
			+'  <label>'
			+'  <input type="checkbox" checked="checked" name="remember" style="margin-bottom:15px">Remember me'
			+'  </label>'
			+'  <p>By creating an account you agree to our <a href="#" style="color:dodgerblue">Terms & Privacy</a>.</p>'
			+'  <div class="clearfix">'
			+'  <button type="button" class="cancelbtn">Cancel</button>'
			+'  <button type="submit" id="join_btn" class="signupbtn">Sign Up</button>'
			+'  </div>'
			+'  </div>'
			+'	</form>'}
}